BABAReasoning/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^babaApp/', include('babaApp.urls')),
    url(r'^admin/', admin.site.urls),
]

babaApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'babaApp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^learn/$', views.learn, name='learn'),
    url(r'^settings/update/(?P<selected_strategy_name>[\w_-|\W]+)/$', views.settings_update, name='settings'),
    url(r'^settings/(?P<selected_strategy_name>[\w_-|\W]+)/$', views.settings, name='settings'),
    url(r'^settings/$', views.settings_default, name='settings'),
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^frameworks/(?P<market_name>[\w-]+)/(?P<username>[\w_-|\W]+)/strategy_action/(?P<strategy_name>[\w_-|\W]+)/(?P<strategy_action_id>[\w_-|\W]+)/$', views.strategy_action, name='frameworks'),
    url(r'^frameworks/(?P<market_name>[\w-]+)/(?P<username>[\w_-|\W]+)/(?P<strategy_name>[\w_-|\W]+)/(?P<delete_element>[\w_-|\W]*)/(?P<type>[\w]+)/$', views.frameworks_with_delete_element, name='frameworks_delete_element'),
    url(r'^frameworks/(?P<market_name>[\w-]+)/(?P<username>[\w_-|\W]+)/(?P<strategy_name>[\w_-|\W]+)/$', views.frameworks, name='frameworks'),
    url(r'^frameworks/(?P<market_name>[\w-]+)/(?P<username>[\w_-|\W]+)/$', views.frameworks_with_market, name='frameworks_with_market'),
    url(r'^frameworks/$', views.frameworks_default, name='frameworks_default'),
    url(r'^analyse/(?P<username>[\w_-|\W]+)/(?P<strategy_name>[\w_-|\W]+)/$', views.analyse, name='analyse'),
    url(r'^random_variables/$', views.random_variables_default, name='random_variables'),
    url(r'^random_variables/(?P<username>[\w_-|\W]+)/$', views.random_variables, name='random_variables'),
    url(r'^marketdata/(?P<instrument_name>[\w-]+)/(?P<duration>[\w]+)/$', views.chart_data, name='chart_data'),
    url(r'^data/empty/$', views.empty, name='empty'),
    url(r'^data/performance/(?P<username>[\w_-|\W]+)/(?P<strategy_name>[\w_-|\W]+)/(?P<start_seconds>[\w\.]+)/(?P<end_seconds>[\w\.]+)/$', views.strategy_performance_data, name='strategy_performance_data'),
    url(r'^data/compare_performance/(?P<username>[\w_-|\W]+)/(?P<strategy_name>[\w_-|\W]+)/(?P<compare_strategy_name>[\w_-|\W]+)/(?P<start_seconds>[\w\.]+)/(?P<end_seconds>[\w\.]+)/$', views.compare_strategy_performance_data, name='strategy_performance_data'),
    url(r'^data/back_test/(?P<username>[\w_-|\W]+)/(?P<strategy_name>[\w_-|\W]+)/(?P<start_seconds>[\w\.]+)/(?P<end_seconds>[\w\.]+)/$', views.back_test_data, name='back_test_data'),
    url(r'^data/compare_back_test/(?P<username>[\w_-|\W]+)/(?P<strategy_name>[\w_-|\W]+)/(?P<compare_strategy_name>[\w_-|\W]+)/(?P<start_seconds>[\w\.]+)/(?P<end_seconds>[\w\.]+)/$', views.compare_back_test_data, name='strategy_performance_data'),
    url(r'^data/semantic_probability/(?P<username>[\w_-|\W]+)/(?P<strategy_name>[\w_-|\W]+)/(?P<sentence>[\w]+)/(?P<semantics>[\w])/$', views.semantic_probability, name='semantic_probability'),
]

babaApp/forms.py
from django import forms
from django.contrib.admin import widgets
from .models import Market, Strategy


class AssumptionForm(forms.Form):
    assumption = forms.CharField(required=True)


class ContraryForm(forms.Form):
    contrary = forms.CharField(required=True)


class RandomVariableForm(forms.Form):
    random_variable = forms.CharField(required=True)


class RuleForm(forms.Form):
    rule = forms.CharField(required=True,
                           label='',
                           help_text='Add a rule. (BUY :- assumption, random variable, other element)')


class MacroRuleForm(forms.Form):
    macro_rule = forms.CharField(required=True,
                           label='',
                           help_text='Add a macro rule. (Uptrend :- 50DayEMA > 100DayEMA and Close > 100DayEMA)')


trading_choices = [('yes', 'YES'), ('no', 'NO')]
trading_options = [(0, 'BUY'), (1, 'SELL'), (2, 'BUY and SELL')]


class SettingsForm(forms.Form):
    enable_trading = forms.MultipleChoiceField(
        widget=forms.RadioSelect,
        choices=trading_choices,
    )
    trading_options = forms.MultipleChoiceField(
        widget=forms.RadioSelect,
        choices=trading_options,
    )
    buy_quantity = forms.IntegerField(
        min_value=0,
    )
    sell_quantity = forms.IntegerField(
        min_value=0,
    )
    required_trade_confidence = forms.FloatField(
        label='Required trade confidence (%)',
        min_value=0.0,
        max_value=100.0
    )
    close_position_yield = forms.FloatField(
        label='Close position yield (%)',
        min_value=0.0,
        max_value=100.0
    )
    close_position_loss_limit = forms.FloatField(
        label='Close position loss limit (%)',
        min_value=0.0,
        max_value=100.0
    )


class StrategyPreferencesSelectionForm(forms.Form):
    strategy_selection = forms.ModelChoiceField(
        queryset=Strategy.objects,
        empty_label=' ',
        widget=forms.Select(attrs={'onchange': 'this.form.submit();'}))


class StrategySelectionForm(forms.Form):
    strategy_selection = forms.ModelChoiceField(
        queryset=Strategy.objects,
        empty_label='select strategy',
        widget=forms.Select(attrs={'onchange': 'this.form.submit();'})
    )


class NewStrategyForm(forms.Form):
    new_strategy = forms.CharField(required=True)


class TimeIntervalSelectionForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()
    compare_strategy = forms.ModelChoiceField(
        queryset=Strategy.objects,
        empty_label=' ',
        label='Compare strategy',
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super(TimeIntervalSelectionForm, self).__init__(*args, **kwargs)
        # self.fields['start_date'].widget = widgets.AdminDateWidget()
        self.fields['end_date'].widget = widgets.AdminDateWidget()


class BackTestTimeIntervalSelectionForm(forms.Form):
    test_start_date = forms.DateTimeField(label='Start date')
    test_end_date = forms.DateTimeField(label='End date')
    test_compare_strategy = forms.ModelChoiceField(
        queryset=Strategy.objects,
        empty_label=' ',
        label='Compare strategy',
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super(BackTestTimeIntervalSelectionForm, self).__init__(*args, **kwargs)
        self.fields['test_start_date'].widget = widgets.AdminDateWidget()
        self.fields['test_end_date'].widget = widgets.AdminDateWidget()

babaApp/databaseController/controller.py
from babaApp.models import User, Market, TradingSettings, Portfolio, Trade, Strategy, Indicator, ExchangeEvent
from django.shortcuts import get_list_or_404
from marketData import services as market_data_services
from StrategyEngine import services as strategy_engine_services
from babaSemantics import BABAProgramParser as Parser, Semantics, formattingUtilities
from babaApp.extras import applicationStrings as strings, converters
from frameworkExtensions import service as framework_extensions_service

DELTA = 0.000001
FLOAT_FORMAT = "{0:.2f}"
NEW_LINE = '\n'

# Returns god user -> for testing
def get_user():
    return User.objects.all()[0]


def get_market_list():
    return get_list_or_404(Market)


def get_first_strategy_for_market(user, market_name):
    strategies = Strategy.objects.filter(
        user=user,
        market__market_name=market_name
    )

    if len(strategies) == 0:
        market = Market.objects.get(market_name=market_name)
        strategy_name = strings.default_strategy_name(market_name)
        new_strategy = Strategy(user=user, market=market, strategy_name=strategy_name)
        new_strategy.save()

    strategies = Strategy.objects.filter(
        user=user,
        market__market_name=market_name
    )

    return strategies[0]


def create_new_strategy(user, market_name, strategy_name):
    market = Market.objects.get(market_name=market_name)
    new_strategy = Strategy(user=user, market=market, strategy_name=strategy_name)
    new_strategy.save()


def get_settings(user, strategy_name):
    settings = TradingSettings.objects.filter(
        user=user,
        strategy__strategy_name=strategy_name)

    if len(settings) == 0:
        strategy = Strategy.objects.get(strategy_name=strategy_name)
        new_settings = TradingSettings(user=user, strategy=strategy, enable_trading=True)
        new_settings.save()

    settings = TradingSettings.objects.get(
        user=user,
        strategy__strategy_name=strategy_name)

    return settings


def get_strategies_for_user(user):
    return Strategy.objects.filter(user=user).order_by('market')


def get_market_for_strategy_name(user, strategy_name):
    return Strategy.objects.get(user=user, strategy_name=strategy_name).market


def get_strategy_index(user, strategy_name):
    # strategies = get_strategies_for_user(user)
    strategies = Strategy.objects.filter(user=user)
    counter = 1
    for s in strategies:
        if s.strategy_name == strategy_name:
            return counter
        counter += 1

    return 0


def get_strategies_for_user_and_market(user, market):
    return Strategy.objects.filter(user=user, market=market).order_by('strategy_name')


# Returns user current total equity and overall percentage change
def get_total_equity(user):  # TODO: plus value of open_positions
    portfolio = Portfolio.objects.get(user=user)
    start = portfolio.start_value
    current = portfolio.current_value
    decimal_change = abs(start - current) / start if current > start else abs(start - current) / start * -1.0

    return FLOAT_FORMAT.format(current), FLOAT_FORMAT.format(decimal_change * 100)


# Returns a list of dictionaries of all current open positions
def get_open_positions(user, market=None):
    open_trades = Trade.objects.filter(open_position=True, portfolio__user=user)
    open_trades = open_trades.filter(strategy__market=market) if market is not None else open_trades
    open_positions = []
    for trade in open_trades:
        current_price = market_data_services.get_latest_price(trade.instrument_symbol, trade.direction)
        open_position = {'symbol': trade.instrument_symbol,
                         'strategy': trade.strategy.strategy_name,
                         'direction': get_direction_string(trade.direction),
                         'quantity': trade.quantity,
                         'price': trade.price,
                         'current_price': current_price,
                         'result': FLOAT_FORMAT.format(trade.direction * get_position_result(trade.price, current_price, trade.quantity)),
                         'percentage_change': FLOAT_FORMAT.format(trade.direction * get_percentage_change(trade.price, current_price))}
        open_positions.append(open_position)

    return open_positions


# Returns a (list of dictionaries) summary of all closed positions
def get_executed_trades(user):
    closed_positions = Trade.objects.filter(open_position=False, portfolio__user=user)
    executed_trades = []
    for position in closed_positions:
        trade = {'symbol': position.instrument_symbol,
                 'direction': get_direction_string(position.direction),
                 'quantity': position.quantity,
                 'price': position.price,
                 'close_price': position.close_price,
                 'result': FLOAT_FORMAT.format(position.direction * get_position_result(position.price, position.close_price, position.quantity)),
                 'percentage_change': FLOAT_FORMAT.format(position.direction * get_percentage_change(position.price, position.close_price))}
        executed_trades.append(trade)

    return executed_trades


# Returns performance summaries for each framework
def get_strategy_performance(user):
    strategies = Strategy.objects.all()
    performances = []
    for strategy in strategies:
        executed_trades = Trade.objects.filter(strategy=strategy, portfolio__user=user, open_position=False)
        invested_in_trades = sum([trade.quantity * trade.price for trade in executed_trades])
        profit = sum([((trade.close_price - trade.price) * trade.quantity * trade.direction) for trade in executed_trades])
        percentage_profit = "0.00" if (invested_in_trades < DELTA) else "{0:.2f}".format(profit / invested_in_trades * 100)
        performance = {'market_name': strategy.market.market_name,
                       'strategy_name': strategy.strategy_name,
                       'profit': FLOAT_FORMAT.format(profit),
                       'percentage_profit': percentage_profit}

        performances.append(performance)

    return performances


def get_direction_string(direction):
    if direction == 1:
        return "BUY"
    elif direction == -1:
        return "SELL"

    return "UNKNOWN" \



def get_position_result(start, end, quantity):
    return (end - start) * quantity


def get_percentage_change(start, end):
    return (end - start) / start * 100


def get_strategy_elements(user, strategy_name):
    strategy = Strategy.objects.filter(user=user, strategy_name=strategy_name)[0]
    strategy_string = strategy.framework

    baba = Parser.BABAProgramParser(string=strategy_string).parse()
    language, assumptions, contraries, rvs, rules = Semantics.string_representation(baba)

    return [language, assumptions, contraries, rvs, rules]


def get_strategy_indicators(user, strategy_name):
    return Indicator.objects.all()


def get_strategy_macro_rules(user, strategy_name):
    strategy = Strategy.objects.filter(user=user, strategy_name=strategy_name)[0]
    if not strategy.framework_extension: return None

    macro_rules = strategy.framework_extension.split(NEW_LINE)
    return_rules = []
    for rule in macro_rules:
        if rule and len(rule.strip()) > 0:
            return_rules.append(rule)

    if len(return_rules) == 0: return None
    return return_rules


def get_strategy_framework(strategy, datetime):
    main_framework = strategy.framework
    additional_random_variables = framework_extensions_service.extract_external_random_variables(main_framework)
    additional_rules = framework_extensions_service.compute_framework_rules(strategy, datetime)
    return main_framework + ' \n ' + additional_random_variables + '\n' + additional_rules


def get_strategy_trades_for_interval(user, strategy_name, start_date, end_date):
    strategy = Strategy.objects.filter(user=user, strategy_name=strategy_name)[0]
    trades = Trade.objects.filter(strategy=strategy, position_opened__gte=start_date, position_opened__lte=end_date)
    trades_list = []
    for trade in trades:
        trade_detail = {
            'trade_type': 'OPEN',
            'quantity': trade.quantity,
            'direction': converters.trade_type_integer_to_string(trade.direction),
            'price': trade.price,
            'date': trade.position_opened,
            'framework': formattingUtilities.get_semantic_probabilities_html(trade.framework_at_open)
        }
        trades_list.append(trade_detail)

        if not trade.open_position:
            close_trade_detail = {
                'trade_type': 'CLOSE',
                'quantity': trade.quantity,
                'direction': converters.trade_type_integer_to_string(trade.direction),
                'price': trade.close_price,
                'date': trade.position_closed,
                'framework': formattingUtilities.get_semantic_probabilities_html(trade.framework_at_close)
            }
            trades_list.append(close_trade_detail)

    return trades_list


# Append to framework string representation with the relevant element
def add_framework_element(user, strategy_name, assumption=None, contrary=None, rv=None, rule=None):
    try:
        strategy = Strategy.objects.get(user=user, strategy_name=strategy_name)
        strategy_extension = '\n'
        if assumption is not None:
            strategy_extension += 'myAsm(' + assumption + ').'
        if contrary is not None:
            strategy_extension += 'contrary(' + contrary + ').'
        if rv is not None:
            strategy_extension += 'myRV(' + rv + ').'
        if rule is not None:
            head = rule.split(':-')[0]
            body = rule.split(':-')[1]
            strategy_extension += 'myRule(' + head + ', [' + body + ']).'

        strategy.framework = (strategy.framework + strategy_extension)
        strategy.save()

    except Strategy.DoesNotExist:
        print('Framework with name ' + strategy_name + ' does not exist')

babaApp/templates/babaApp/analyse.html
<!DOCTYPE HTML>
<!--
	Prologue by HTML5 UP
	html template: https://html5up.net/prologue
-->
{% load static %}
<html>
	<head>
		<title>BabaStrat</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="{% static 'babaApp/assets/js/ie/html5shiv.js' %}"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'babaApp/assets/css/main.css' %}" />
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static 'babaApp/assets/css/ie8.css' %}" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static 'babaApp/assets/css/ie9.css' %}" /><![endif]-->
	</head>
	<body onLoad='setupAnalyseCharts()'>

        <!-- Header: (sidebar) -->
            {% include "babaApp/sideBar.html" %}
        <!-- end of sidebar -->

		<!-- Main -->
			<div id="main">

                <section class="three">
                        <div style="width:100%; height:25px; position:relative">
                            <div align="left" style="float:left">
                                <p2 style="margin-left:50px">Analyse strategy</p2>

                                <p id="strategy_name" hidden>{{ strategy_name }}</p>
                                <p id="username" hidden>{{ username }}</p>
                                <p id="strategy_performance_data_url" hidden>{{ strategy_performance_data_url }}</p>
                                <p id="back_test_data_url" hidden>{{ back_test_data_url }}</p>
                            </div>
                            <div align="right" style="float:right; margin-right:50px">
                                <p2 id="strategy_name" style="margin-right:50px">({{ strategy_name }})</p2>
                            </div>
                        </div>
                    </section>

                <!-- Strategy performance section -->
                <section id="strategy_performance" style="margin-top:0px">
                    <p>Strategy performance</p>
                    <div id="analyse_chart_div">
                        <canvas id="performanceChart" width="700" height="450"></canvas>
                    </div>
                    <div id="analyse_chart_options_div">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ time_interval_form }}
                            <input type="submit" value="Recalculate" style="width:100%;height:40px;padding:0px;margin-top:20px">
                        </form>
                    </div>
                    {% if strategy_trades %}
                    <div id="analyse_trade_details" class="divBorder">
                        <table class="layout_table">
                            <th><b>Type</b></th>
                            <th><b>Quantity</b></th>
                            <th><b>Direction</b></th>
                            <th><b>Price</b></th>
                            <th><b>Date</b></th>

                            {% for t in strategy_trades %}
                            <tr onclick="strategy_trade_detail('{{ t.framework }}')">
                                <td>{{t.trade_type}}</td>
                                <td>{{t.quantity}}</td>
                                <td>{{t.direction}}</td>
                                <td>{{t.price}}</td>
                                <td>{{t.date}}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                    {% endif %}
                </section>

                 <!-- Back test strategy section -->
                <section id="back_test_strategy" style="margin-top:0px">
                    <p>Back test strategy</p>
                    <div id="analyse_test_chart_div">
                        <canvas id="backTestChart" width="700" height="400"></canvas>
                    </div>
                    <div id="analyse_test_chart_options_div">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ back_test_time_interval_form }}
                            <input type="submit" value="Simulate" style="width:100%;height:40px;padding:0px;margin-top:20px">
                        </form>
                    </div>
                </section>

			</div>

		<!-- Footer -->
			<div id="footer">

                <ul class="copyright">
                    <li>Equity <b>GBP 10000</b></li>
                    <li>GBP/USD position value <b>GBP -897.23</b></li>
                </ul>

			</div>

		<!-- Scripts -->
        <script src="{% static 'babaApp/assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'babaApp/assets/js/jquery.scrolly.min.js' %}"></script>
        <script src="{% static 'babaApp/assets/js/jquery.scrollzer.min.js' %}"></script>
        <script src="{% static 'babaApp/assets/js/skel.min.js' %}"></script>
        <script src="{% static 'babaApp/assets/js/util.js' %}"></script>
        <!--[if lte IE 8]><script src="{% static 'babaApp/assets/js/ie/respond.min.js' %}"></script><![endif]-->
        <script src="{% static 'babaApp/assets/js/main.js' %}"></script>
        <script src="{% static 'babaApp/assets/js/Chart.min.js' %}"></script>
        <script src="{% static 'babaApp/assets/js/historicalDataCharting.js' %}"></script>

        <!--<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %} "/>-->
        <!--<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %} "/>-->
        <!--<link rel="stylesheet" type="text/css" href="{% static 'admin/css/global.css' %}"/>-->
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>


        <!--take from: https://stackoverflow.com/questions/38601/using-django-time-date-widgets-in-custom-form-->
        <script src="/admin/jsi18n/"></script>
        <script src="{% static 'admin/js/core.js' %}"></script>
        <script src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
        <script src="{% static 'admin/js/jquery.js' %}"></script>
        <!--<script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>-->
        <script src="{% static 'admin/js/actions.js' %}"></script>
        <script src="{% static 'admin/js/calendar.js' %}"></script>
        <script src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>

	</body>


    <div id="strategy_trade_detail_overlay" style='visibility:hidden'>
        Semantic Probabilities
        <div id="semantic_probabilities_div"></div>
        <button class="overlay_cancel_button" onclick="remove_strategy_trade_detail_overlay()">Cancel</button>
    </div>
</html>

babaApp/templates/babaApp/index.html
<h1>This is the index page</h1>

babaApp/templates/babaApp/settings.html
<!DOCTYPE HTML>
<!--
	Prologue by HTML5 UP
	html template: https://html5up.net/prologue
-->
{% load static %}
<html>
	<head>
		<title>BabaStrat</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="{% static 'babaApp/assets/js/ie/html5shiv.js' %}"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'babaApp/assets/css/main.css' %}" />
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static 'babaApp/assets/css/ie8.css' %}" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static 'babaApp/assets/css/ie9.css' %}" /><![endif]-->
	</head>
	<body>

        <!-- Header: (sidebar) -->
            {% include "babaApp/sideBar.html" %}
        <!-- end of sidebar -->

		<!-- Main -->
			<div id="main">

				<!-- Header -->

                    <section class="four">
                        <div style="width:100%; height:25px; position:relative">
                            <div align="left" style="float:left">
                                <p2 style="margin-left:20px">Trading Preferences</p2>

                                <p id="strategy_name" hidden>{{ strategy_name }}</p>
                                <p id="username" hidden>{{ username }}</p>
                            </div>
                            <div align="right" style="float:right; margin-right:50px">
                                {% if selected_strategy %}
                                <p2 id="strategy_name" style="margin-left:50px">({{ selected_strategy }})</p2>
                                {% endif %}
                            </div>
                        </div>
                    </section>

                <!-- Form -->
                <section id="settings_section" class="two">
                    <div id="form_div" class="container">
                        <form role="form" action="" method="post">
                            {% csrf_token %}
                            {{ strategy_selection_form }}
                        </form>

                        <form role="form" action="{% url 'babaApp:settings' %}update/{{selected_strategy}}/" method="post">
                            {% csrf_token %}
                            {{ settings_form }}

                            <br><br>

                            <input type="submit" value="Update">
                        </form>
                    </div>
                </section>

				<!-- Term definitions -->
					<section id="positions" class="three">
						<div class="container divBorder">
                            <h3>Term definitions</h3>
                            <p><strong>Enable trading: </strong>when enabled, your trading strategies will be executed under the specified conditions</p>
                            <p><strong>Trading options: </strong>select which trading strategies should tracked</p>
                            <p><strong>Required trade confidence: </strong>trades will only be executed when the semantic probability, a measure of confidence according to your defined strategy, reaches the specified level</p>
                            <p><strong>Close position yield: </strong>open trading positions will be closed once profit is at the chosen level</p>
                            <p><strong>Close position loss limit</strong>open trading positions that perform unexpectedly will be closed to limit losses, defined as a maximum acceptable percentage loss</p>
						</div>
					</section>

			</div>

		<!-- Footer -->
			<div id="footer">
                <ul class="copyright">
                    <li>Equity <b>GBP 10000</b></li>
                    <li>GBP/USD position value <b>GBP -897.23</b></li>
                </ul>
			</div>

		<!-- Scripts -->
			<script src="{% static 'babaApp/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'babaApp/assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'babaApp/assets/js/jquery.scrollzer.min.js' %}"></script>
			<script src="{% static 'babaApp/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'babaApp/assets/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="{% static 'babaApp/assets/js/ie/respond.min.js' %}"></script><![endif]-->
			<script src="{% static 'babaApp/assets/js/main.js' %}"></script>

	</body>
</html>

babaApp/templates/babaApp/sideBar.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
		<!-- Header -->
			<div id="header">

				<div class="top">

					<!-- Logo -->
						<div id="logo">
							<h1 id="title">BabaStrat</h1>
							<p>Creating alphas with BABAs</p>
						</div>

					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li><a href="{% url 'babaApp:learn' %}" id="learn-link" class="skel-layers-ignoreHref" style="{{ style.learn_li }}"><span class="icon fa-lightbulb-o" style="{{ style.learn_span }}">Learn</span></a></li>
								<li><a href="{% url 'babaApp:settings' %}" id="settings-link" class="skel-layers-ignoreHref" style="{{ style.settings_li }}"><span class="icon fa-cogs" style="{{ style.settings_span }}">Preferences</span></a></li>
								<li><a href="{% url 'babaApp:reports' %}" id="reports-link" class="skel-layers-ignoreHref" style="{{ style.reports_li }}"><span class="icon fa-bar-chart" style="{{ style.reports_span }}">Reports</span></a></li>
								<li><a href="{% url 'babaApp:random_variables' %}" id="random_variables-link" class="skel-layers-ignoreHref" style="{{ style.random_variables_li }}"><span class="icon fa-pie-chart" style="{{ style.random_variables_span }}">Variables</span></a></li>
							</ul>
						</nav>

						<div id="frameworksList" class="container frameworksSidebar">
                            <section>
                                <h5>Frameworks</h5>
                                <div class="frameworksScroll">
                                    <ul class="frameworksList">

                                        {% if markets %}
                                        {% for market in markets %}
                                        <li><a href="{% url 'babaApp:frameworks_with_market' market_name=market.market_name username=username %}">{{ market.market_name }}</a></li>
                                        {% endfor %}
                                        {% endif %}

                                    </ul>
                                </div>
                            </section>
						</div>

				</div>

				<div class="bottom">

					<!-- Social Icons -->
						<ul class="icons">
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
							<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
							<li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
						</ul>

				</div>

			</div>

</body>
</html>